[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mongod]
command=mongod --bind_ip 127.0.0.1 --dbpath /data/db --logpath /var/log/supervisor/mongod.log
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/mongod.log
stderr_logfile=/var/log/supervisor/mongod-err.log

[program:app]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/app/backend
autostart=true
autorestart=true
priority=20
startsecs=5
stdout_logfile=/var/log/supervisor/app.log
stderr_logfile=/var/log/supervisor/app-err.log
environment=PYTHONDONTWRITEBYTECODE="1",PYTHONUNBUFFERED="1"
